spring:
  data:
    mongodb:
      host: 192.168.1.176
      database: pigeondb
      port: 27017
      username: yiming
      password: '123456'

logging:
  level:
    club.maddm.king.pigeon.web.controller: debug
    club.maddm.king.pigeon.web.mapper: debug
    club.maddm.king.pigeon.core.mapper: debug
    org.springframework.data.mongodb.core: DEBUG
    org.springframework: DEBUG